BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Characters] (
    [id] INT NOT NULL IDENTITY(1,1),
    [name] NVARCHAR(1000) NOT NULL,
    [status] NVARCHAR(1000) NOT NULL,
    [species] NVARCHAR(1000) NOT NULL,
    [type] NVARCHAR(1000),
    [gender] NVARCHAR(1000) NOT NULL,
    [image] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [Characters_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [Characters_name_key] UNIQUE NONCLUSTERED ([name])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
