BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Characters] ADD [createdAt] DATETIME2 NOT NULL CONSTRAINT [Characters_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
[updatedAt] DATETIME2 CONSTRAINT [Characters_updatedAt_df] DEFAULT CURRENT_TIMESTAMP;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
