export const TOKENSORM = {
  USER_TRANSACTION: 'USER_TRANSACTION',
  USER_REPOSITORY: 'USER_REPOSITORY',
  ORDER_REPOSITORY: 'ORDER_REPOSITORY',
  DATA_SOURCE: 'DATA_SOURCE',
};

export const USERNAME_ADMIN = 'admin';
export const PASSWORD_ADMIN = 'admin';
